name: Oratio Project
description: 

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount

# translation tags
t:
  ita:
    home:  "Home"
    developer: "Sviluppatori"
    demo : "Demo online"
    use : "Usa online"
    about: "About"
    contact : "Contatti"
    menu: "Menù principale"
    account : "Conto clienti"
    products : "Prodotti e risorse"
    finance : "Finanza"
    settings: "Impostazioni generali"
    language : "Lingua"
    back_to_top : "Torna su"
  eng:
    home:  "Home"
    developer : "Developer"
    demo: "Online demo"
    use : "Online use"
    about: "About"
    contact : "Contact"
    menu: "Main menu"
    account : "Account receivable"
    products : "Products and resources"
    finance : "Finance"
    settings: "General settings"
    language : "Language"
    back_to_top : "Back to top"