name: Oratio Project
description: 

url: "http://oratio-project.github.io"

paginate: 10

markdown: rdiscount

# translation tags
t:
  ita:
    home:  "Home"
    developer: "Sviluppatori"
    install : "Installazione"
    demo : "Demo online"
    use : "Usa online"
    about: "About"
    contact : "Contatti"
    menu: "Menù Principale"
    account : "Acquisti e Vendite"
    products : "Risorse e Prodotti&Servizi"
    finance : "Contabilità e controllo di gestione"
    settings: "Impostazioni generali e amministrazione"
    language : "Lingua"
    requirements : "Prerequisiti"
    installation : "Installazione"
    postgreSQL : "Installazione e configurazione del database PostgreSQL"
    perl : "Installazione moduli Perl"
    jasper : "Configurazione ambiente per stampe JasperReports"
    config : "Configurazione di Oratio® · Prima installazione"
    access : "Accesso al programma"
    back_to_top : "Torna su"
  eng:
    home:  "Home"
    developer : "Developer"
    install : "Installation"
    demo: "Online demo"
    use : "Online use"
    about: "About"
    contact : "Contact"
    menu: "Main menu"
    account : "Accounts Receivable and Accounts Payable"
    products : "Resources and Products&Services"
    finance : "Finance and management control"
    settings: "General settings and administration"
    language : "Language"
    requirements : "Requirements"
    installation : "Installation"
    postgreSQL : "Installation and configuration of PostgreSQL database"
    perl : "Installation of Perl modules"
    jasper : "Configuration of JasperReports"
    config : "Configuration of Oratio® · First installation"
    access : "Access to the programm"
    back_to_top : "Back to top"